server:
  port: 8082

grpc:
  server:
    port: 9091
    enable-keep-alive: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/space_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: telemetry-service
      auto-offset-reset: earliest
