server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: mission-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.example.kafka.dto

app:
  space-center-service:
    url: ${SERVER_URL:http://localhost:8080/api}
    missions:
        - targetType: CONSTELLATION
          constellationName: "GeoStationary"
          cron: "0 0 */6 * * *"  # каждые 6 часов
        - targetType: SINGLE_SATELLITE
          constellationName: "LowOrbit"
          satelliteName: "Sat-1"
          cron: "0 30 8 * * MON"  # каждый понедельник в 8:30
        - targetType: CONSTELLATION
          constellationName: "Орбита-1"
          cron: "0 */1 * * * *"   # каждую минуту
