spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/space_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2s
  cache:
    type: redis
    redis:
      cache-null-values: false

server:
  port: 8080

grpc:
  telemetry:
    host: localhost
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    caches:
      enabled: true
  metrics:
    enable:
      cache: true
  health:
    redis:
      enabled: false

app:
  outbox:
    relay-interval-ms: 5000
