server:
  port: 8080

grpc:
  telemetry:
    host: localhost
    port: 9091

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/space_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

